import type { Metadata } from "next";
import { Montserrat, Outfit } from "next/font/google";
import "./globals.css";

const monst = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--montserrat",
});
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--outift",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={monst.variable}>
      <body className={monst.className}>{children}</body>
    </html>
  );
}
